### ISSUE TITLE
Plugin fails upon update to OBS 27.2.X on Windows

### ISSUE THREAD

**Issue by jdudetv** [summershrimp/obs-ssp#60]
Similar issue as the Mac OS one brought up a couple days ago but its Windows now. fixes put in place don't rectify the issue on windows 10.

In the OBS Devs words "For windows, the plugin probably needs to be rebuilt against the newer versions of ffmpeg dlls".

`17:38:45.581: Failed to load 'en-GB' text for module: 'obs-ssp.dll'
17:38:45.581: [obs-ssp] hello ! (obs-ssp version 0.9.2) size: 384
17:38:45.581: LoadLibrary failed for 'libssp.dll': The specified module could not be found.
17:38:45.581:  (126)
17:38:45.581: [obs-ssp] Load libssp.dll failed.
17:38:45.581: Failed to initialize module 'obs-ssp.dll'`

**Comment by summershrimp** [comment]
Thanks for reporting, I'd look at it ASAP.

**Comment by summershrimp** [comment]
In a quick analysis, it's not related with ffmpeg. Maybe the compiler environment for imagevision's libssp.dll is not compatible to newer version of obs-studio.

**Comment by jdudetv** [comment]
Eyy that did it. thanks for the temp fix.
