### ISSUE TITLE
Cannot compile on MacOS 12.16.3

### ISSUE THREAD

**Issue by gahbes** [summershrimp/obs-ssp#74]
Using GitHub script (/obs-ssp/.github/scripts/build-macos.zsh) fails with "CMake Error: Xcode 1.5 not supported." with latest Xcode cmd tools installed.

Compiling OBS-SSP inside OBS (v29) plugin folder as part of OBS Studio build script (/obs-studio/CI/build-macos.sh) fails with..

CMake Error at plugins/obs-ssp/CMakeLists.txt:41 (find_package):
  By not providing "Findlibobs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libobs", but
  CMake did not find one.

  Could not find a package configuration file provided by "libobs" with any
  of the following names:

    libobsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "libobs" to CMAKE_PREFIX_PATH or set
  "libobs_DIR" to a directory containing one of the above files.  If "libobs"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by summershrimp** [comment]
Just use `build-macos.zsh`, don't put it inside obs-studio's repository.
Maybe you need to use `xcode-select` to change the global effected XCode version.
On my 3 dev environment (macOS 12.15 12.16 13.1 with various XCode version), Only need to install brew to use build-macos.zsh

**Comment by gahbes** [comment]
Got it working, thanks! Had to accept Xcode license.
