### ISSUE TITLE
Does not load Mac OBS 29.1.1

### ISSUE THREAD

**Issue by andrewfitz** [summershrimp/obs-ssp#78]
Plugin fails to load due to issue from log:

`15:25:28.442: os_dlopen(/Users/*****/Library/Application Support/obs-studio/plugins/obs-ssp.plugin/Contents/MacOS/obs-ssp->/Users/*****/Library/Application Support/obs-studio/plugins/obs-ssp.plugin/Contents/MacOS/obs-ssp): dlopen(/Users/******/Library/Application Support/obs-studio/plugins/obs-ssp.plugin/Contents/MacOS/obs-ssp, 0x0101): Library not loaded: @rpath/libavcodec.59.37.100.dylib
15:25:28.442:   Referenced from: <D322B198-F7C6-3575-9156-1A7891E169AF> /Users/*****/Library/Application Support/obs-studio/plugins/obs-ssp.plugin/Contents/MacOS/obs-ssp
15:25:28.442:   Reason: tried: '/Applications/OBS.app/Contents/Frameworks/libavcodec.59.37.100.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libavcodec.59.37.100.dylib' (no such file), '/usr/lib/libavcodec.59.37.100.dylib' (no such file, not in dyld cache)`

**Comment by summershrimp** [comment]
Thanks for report, currently working on it #77 77

**Comment by JohanNicander** [comment]
Meanwhile you can symlink the missing libraries to those already in obs.

**Comment by matteatsmochi** [comment]
Quick add to this report, it is also an issue on Windows as well. I believe it started with 29.1.0, I've rolled back to 29.0.2 for it to work.

**Comment by summershrimp** [comment]
Updated #77
