### ISSUE TITLE
Does not work with OBS 30.1.2

### ISSUE THREAD

**Issue by gahbes** [summershrimp/obs-ssp#79]
Plugin loads but neither audio or video is playing.

**Comment by matteatsmochi** [comment]
I can help with mine log files.

[2024-07-26 14-55-04.txt](https://github.com/user-attachments/files/16397006/2024-07-26.14-55-04.txt)

**Comment by summershrimp** [comment]
> I can help with my log files. Looks like the errors are:
> 
> > 14:55:05.117: Skipping module '../../obs-plugins/64bit/libssp.dll', not an OBS plugin
> 
> > 14:55:05.495: LoadLibrary failed for '../../obs-plugins/64bit/obs-ssp.dll': The specified module could not be found.
> 
> > 14:55:05.495: Module '../../obs-plugins/64bit/obs-ssp.dll' not loaded
> 
> [2024-07-26 14-55-04.txt](https://github.com/user-attachments/files/16397006/2024-07-26.14-55-04.txt)

thanks, it may need to be recompile. I'll release soon.

**Comment by nazoren** [comment]
Hello,
Do you have any news?

**Comment by summershrimp** [comment]
> Hello, Do you have any news?

I'm a little busy these days, should be fix it asap

**Comment by summershrimp** [comment]
we won't support 30.1.2, support for 30.2 and later will be release soon
